---

- name: update Windows
  ignore_errors: yes
  ansible.windows.win_updates:
    category_names: '*'
    log_path: "{{log_path}}"
    state: installed
    reboot: true
    server_selection: windows_update
    blacklist:
      - 576b0dd6-57cc-457n-a5ec-e888491b395d#    

- name: Set execution policy for current session
  win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force
