---

- name: update Windows
  ignore_errors: yes
  ansible.windows.win_updates:
    category_names: '*'
    log_path: "{{log_path}}"
    state: installed
    reboot: true
    server_selection: windows_update
    blacklist:
      - "KB5034441"

- name: Set execution policy for current session
  win_shell: Set-ExecutionPolicy Bypass -Scope Process -Force
